services:
  app:
    env_file:
      - .docker.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flash-sale-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - flash-sale-network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=flash_sale
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: mysql:8.0
    container_name: flash-sale-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: flash_sale
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - flash-sale-network
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    restart: unless-stopped
    networks:
      - flash-sale-network

  web:
    image: nginx:alpine
    container_name: flash-sale-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flash-sale-network
    depends_on:
      - app

networks:
  flash-sale-network:
    driver: bridge

volumes:
  db-data:
